### ISSUE TITLE
Fatal error when viewing Organization

### ISSUE THREAD

**Issue by mindblender** [phpcollab/phpcollab#65]
Getting a Fatal Error when viewing "Organization Details" from Admin screen

Error:
```
FATAL ERROR (2): TypeError: Argument 1 passed to Laminas\Escaper\Escaper::escapeHtml() must be of the type string, null given, called in [[path]]/classes/Organizations/Organizations.php on line 283 and defined in [[path]]/vendor/laminas/laminas-escaper/src/Escaper.php:180
Stack trace:
#0 [[path]]/classes/Organizations/Organizations.php(283): Laminas\Escaper\Escaper->escapeHtml(NULL)
#1 [[path]]/classes/Organizations/Organizations.php(171): phpCollab\Organizations\Organizations->escapeOrg(Array)
#2 [[path]]/administration/mycompany.php(139): phpCollab\Organizations\Organizations->getOrganizationById(1)
#3 {main}
```

**Comment by mindblender** [comment]
Fixed in v2.10.1
